# -*- restclient -*-

POST http://localhost:3000/api/submit
Content-Type: application/json
{
  "quote": "I am"
}

#

POST http://localhost:3000/api/login
Content-Type: application/json
{
  "email": "root@root.org",
  "password": "1337"
}

#
# Replace token with the result from the previous query

POST http://localhost:3000/api/whoami
Content-Type: application/json
{
  "token": "2fe3917b2bedaf03500d53b35397e633"
}

#

GET http://localhost:3000/api/lastmessage
Content-Type: application/json
{}

#

POST http://localhost:3000/api/message
Content-Type: application/json
{
  "messageID": 1
}

#

POST http://localhost:3000/admin/admins
Content-Type: application/json
{}